using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using PetroVisorLite.Domain;
using PetroVisorLite.Domain.Enums;
using PetroVisorLite.Infrastructure.Identity;
using PetroVisorLite.Infrastructure.Seeding;
using static PetroVisorLite.Infrastructure.Identity.Roles;

namespace PetroVisorLite.Infrastructure.Seed;

/// <summary>
/// Seeds demo data: roles, demo users, facilities, wells, and production records.
/// Idempotent — checks whether domain data already exists before doing any work, so it is
/// safe to invoke on every startup without duplicating rows or hitting unique-constraint errors.
///
/// Invocation is controlled by the <c>Seeding:Enabled</c> configuration flag (see Program.cs),
/// NOT by ASPNETCORE_ENVIRONMENT — this lets a demo/staging deployment opt in explicitly via
/// config/env var without being tied to the Development environment name.
///
/// DEV-ONLY: the seeded user passwords below are placeholders for local development/demo
/// purposes only and are never used in production. Enabling <c>Seeding:Enabled</c> against a
/// database that should stay empty (e.g. real production data) is the caller's responsibility.
///
/// Domain data (facilities/wells/production records) comes from Obi-Wan's
/// <see cref="RealisticSeedDataGenerator"/> — a realistic Permian Basin dataset (3 facilities,
/// 14 wells, Arps hyperbolic decline, correlated GOR/WOR trends, and scripted production-loss
/// events). That class is pure data generation (no EF/DbContext dependency); this class owns
/// the persistence + idempotency/flag gating.
/// </summary>
public static class SeedData
{
    private const string DevOnlySeedPassword = "DevOnly!Passw0rd"; // DEV-ONLY, not a production secret.

    public static async Task SeedAsync(PetroVisorDbContext dbContext, RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager, ILogger logger)
    {
        await SeedRolesAsync(roleManager);
        await SeedUsersAsync(userManager);

        // Idempotency check: Wells is the most specific/central table generated by this seeder,
        // so checking it (rather than Facilities) avoids re-seeding if a partial/older seed only
        // ever created facilities.
        if (await dbContext.Wells.AnyAsync())
        {
            logger.LogInformation("Seed data already present — skipping domain data seeding.");
            return;
        }

        logger.LogInformation("Seeding demo facilities, wells, and production records...");

        var generated = RealisticSeedDataGenerator.Generate();
        var facilities = generated.Facilities;
        var wells = generated.Wells;
        var records = generated.Records;

        dbContext.Facilities.AddRange(facilities);
        dbContext.Wells.AddRange(wells);
        dbContext.ProductionRecords.AddRange(records);

        await dbContext.SaveChangesAsync();
        logger.LogInformation("Seeded {FacilityCount} facilities, {WellCount} wells, {RecordCount} production records.",
            facilities.Count, wells.Count, records.Count);
    }

    private static async Task SeedRolesAsync(RoleManager<IdentityRole> roleManager)
    {
        foreach (var role in new[] { Roles.Engineer, Roles.Viewer })
        {
            if (!await roleManager.RoleExistsAsync(role))
            {
                await roleManager.CreateAsync(new IdentityRole(role));
            }
        }
    }

    private static async Task SeedUsersAsync(UserManager<ApplicationUser> userManager)
    {
        await EnsureUserAsync(userManager, "engineer@petrovisor.local", "Demo Engineer", Roles.Engineer);
        await EnsureUserAsync(userManager, "viewer@petrovisor.local", "Demo Viewer", Roles.Viewer);
    }

    private static async Task EnsureUserAsync(UserManager<ApplicationUser> userManager, string email, string displayName, string role)
    {
        var existing = await userManager.FindByEmailAsync(email);
        if (existing is not null)
        {
            return;
        }

        var user = new ApplicationUser
        {
            UserName = email,
            Email = email,
            DisplayName = displayName,
            EmailConfirmed = true,
        };

        var result = await userManager.CreateAsync(user, DevOnlySeedPassword);
        if (result.Succeeded)
        {
            await userManager.AddToRoleAsync(user, role);
        }
    }
}
